### ISSUE TITLE
PLugin just doesn't work

### ISSUE THREAD

**Issue by imperialguy** [jenkinsci/proxmox-plugin#16]
When I tried to save a new node using proxmox VM as slave the get this error:

```
Caused: java.lang.Error: Failed to instantiate class org.jenkinsci.plugins.proxmox.VirtualMachineSlave from {"name":"sample","datacenterDescription":"root@pam - hypervisor.steamngin.com","datacenterNode":"hypervisor","virtualMachineId":"108","snapshotName":"current","startVM":true,"revertPolicy":"AFTER_CONNECT","nodeDescription":"","startupWaitingPeriodSeconds":"60","numExecutors":"1","remoteFS":"/home/steamuser/_work/jenkins","labelString":"","mode":"NORMAL","":["hudson.plugins.sshslaves.SSHLauncher","hudson.slaves.RetentionStrategy$Demand"],"delegateLauncher":{"stapler-class":["hudson.slaves.JNLPLauncher","hudson.slaves.CommandLauncher","hudson.plugins.sshslaves.SSHLauncher"],"host":"hyp-ci-redhat-runner-01.steamngin.com","includeUser":"false","credentialsId":"steamuser","":"3","sshHostKeyVerificationStrategy":{"stapler-class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy","$class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"},"port":"22","javaPath":"","jvmOptions":"","prefixStartSlaveCmd":"","suffixStartSlaveCmd":"","launchTimeoutSeconds":"","maxNumRetries":"","retryWaitTime":"","tcpNoDelay":true,"workDir":""},"retentionStrategy":{"stapler-class":["hudson.slaves.RetentionStrategy$Always","hudson.slaves.SimpleScheduledRetentionStrategy","hudson.slaves.RetentionStrategy$Demand"],"inDemandDelay":"1","idleDelay":"1"},"nodeProperties":{"stapler-class-bag":"true"},"type":"org.jenkinsci.plugins.proxmox.VirtualMachineSlave","Jenkins-Crumb":"62a0bb74bafea87ba08933fe5aa3d547fad215892f6a1b9470b034987e6f953b"}
	at hudson.model.Descriptor.newInstance(Descriptor.java:606)
	at hudson.model.ComputerSet.doDoCreateItem(ComputerSet.java:297)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
Caused: java.lang.reflect.InvocationTargetException
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:400)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
	at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
	at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$2.doDispatch(MetaClass.java:220)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.lang.Thread.run(Thread.java:748)
2021-04-15 10:44:12.653+0000 [id=16]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 2344e2e6-3356-4fb0-82c0-8d0cb7ed3a5a
java.lang.ClassNotFoundException: ["hudson.slaves.JNLPLauncher","hudson.slaves.CommandLauncher","hudson.plugins.sshslaves.SSHLauncher"]
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:2179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:681)
Caused: java.lang.IllegalArgumentException: Class ["hudson.slaves.JNLPLauncher","hudson.slaves.CommandLauncher","hudson.plugins.sshslaves.SSHLauncher"] is specified in JSON, but no such class found in classLoader hudson.PluginManager$UberClassLoader
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:686)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class hudson.slaves.ComputerLauncher from {"stapler-class":["hudson.slaves.JNLPLauncher","hudson.slaves.CommandLauncher","hudson.plugins.sshslaves.SSHLauncher"],"host":"hyp-ci-redhat-runner-01.steamngin.com","includeUser":"false","credentialsId":"steamuser","":"3","sshHostKeyVerificationStrategy":{"stapler-class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy","$class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"},"port":"22","javaPath":"","jvmOptions":"","prefixStartSlaveCmd":"","suffixStartSlaveCmd":"","launchTimeoutSeconds":"","maxNumRetries":"","retryWaitTime":"","tcpNoDelay":true,"workDir":""}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:693)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:490)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:799)
Caused: java.lang.IllegalArgumentException: Failed to convert the delegateLauncher parameter of the constructor public org.jenkinsci.plugins.proxmox.VirtualMachineSlave(java.lang.String,java.lang.String,java.lang.String,java.lang.String,hudson.model.Node$Mode,java.lang.String,hudson.slaves.ComputerLauncher,hudson.slaves.RetentionStrategy,java.util.List,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.Boolean,int,org.jenkinsci.plugins.proxmox.VirtualMachineLauncher$RevertPolicy) throws hudson.model.Descriptor$FormException,java.io.IOException
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:801)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:85)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:690)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class org.jenkinsci.plugins.proxmox.VirtualMachineSlave from {"name":"sample","datacenterDescription":"root@pam - hypervisor.steamngin.com","datacenterNode":"hypervisor","virtualMachineId":"108","snapshotName":"current","startVM":true,"revertPolicy":"AFTER_CONNECT","nodeDescription":"","startupWaitingPeriodSeconds":"60","numExecutors":"1","remoteFS":"/home/steamuser/_work/jenkins","labelString":"","mode":"NORMAL","":["hudson.plugins.sshslaves.SSHLauncher","hudson.slaves.RetentionStrategy$Demand"],"delegateLauncher":{"stapler-class":["hudson.slaves.JNLPLauncher","hudson.slaves.CommandLauncher","hudson.plugins.sshslaves.SSHLauncher"],"host":"hyp-ci-redhat-runner-01.steamngin.com","includeUser":"false","credentialsId":"steamuser","":"3","sshHostKeyVerificationStrategy":{"stapler-class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy","$class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"},"port":"22","javaPath":"","jvmOptions":"","prefixStartSlaveCmd":"","suffixStartSlaveCmd":"","launchTimeoutSeconds":"","maxNumRetries":"","retryWaitTime":"","tcpNoDelay":true,"workDir":""},"retentionStrategy":{"stapler-class":["hudson.slaves.RetentionStrategy$Always","hudson.slaves.SimpleScheduledRetentionStrategy","hudson.slaves.RetentionStrategy$Demand"],"inDemandDelay":"1","idleDelay":"1"},"nodeProperties":{"stapler-class-bag":"true"},"type":"org.jenkinsci.plugins.proxmox.VirtualMachineSlave","Jenkins-Crumb":"62a0bb74bafea87ba08933fe5aa3d547fad215892f6a1b9470b034987e6f953b"}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:693)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:490)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:486)
	at hudson.model.Descriptor.newInstance(Descriptor.java:598)
Caused: java.lang.Error: Failed to instantiate class org.jenkinsci.plugins.proxmox.VirtualMachineSlave from {"name":"sample","datacenterDescription":"root@pam - hypervisor.steamngin.com","datacenterNode":"hypervisor","virtualMachineId":"108","snapshotName":"current","startVM":true,"revertPolicy":"AFTER_CONNECT","nodeDescription":"","startupWaitingPeriodSeconds":"60","numExecutors":"1","remoteFS":"/home/steamuser/_work/jenkins","labelString":"","mode":"NORMAL","":["hudson.plugins.sshslaves.SSHLauncher","hudson.slaves.RetentionStrategy$Demand"],"delegateLauncher":{"stapler-class":["hudson.slaves.JNLPLauncher","hudson.slaves.CommandLauncher","hudson.plugins.sshslaves.SSHLauncher"],"host":"hyp-ci-redhat-runner-01.steamngin.com","includeUser":"false","credentialsId":"steamuser","":"3","sshHostKeyVerificationStrategy":{"stapler-class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy","$class":"hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"},"port":"22","javaPath":"","jvmOptions":"","prefixStartSlaveCmd":"","suffixStartSlaveCmd":"","launchTimeoutSeconds":"","maxNumRetries":"","retryWaitTime":"","tcpNoDelay":true,"workDir":""},"retentionStrategy":{"stapler-class":["hudson.slaves.RetentionStrategy$Always","hudson.slaves.SimpleScheduledRetentionStrategy","hudson.slaves.RetentionStrategy$Demand"],"inDemandDelay":"1","idleDelay":"1"},"nodeProperties":{"stapler-class-bag":"true"},"type":"org.jenkinsci.plugins.proxmox.VirtualMachineSlave","Jenkins-Crumb":"62a0bb74bafea87ba08933fe5aa3d547fad215892f6a1b9470b034987e6f953b"}
	at hudson.model.Descriptor.newInstance(Descriptor.java:606)
	at hudson.model.ComputerSet.doDoCreateItem(ComputerSet.java:297)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
	at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
	at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:816)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$2.doDispatch(MetaClass.java:220)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Maxhy** [comment]
@imperialguy Which Jenkins version are you using?

**Comment by imperialguy** [comment]
The latest

**Comment by nmani** [comment]
I'm running into this same exact issue also on 2.277.4 LTS and 2.293.

**Comment by Dasmandr** [comment]
Same here. I can't add a Proxmox node.
Jenkins: 2.289.1
Java: openjdk version "11.0.11" 2021-04-20

Do you have, at least, a node config.xml example to try to play with it?

Thank you.

**Comment by skoslowski** [comment]
Same here. I am using Jenkins 2.289.3 and have started from a vanilla config. Just added a datacenter and tried to add a node.

**Comment by skoslowski** [comment]
The libvirt-slave-plugin had a similar issue. The fix in https://github.com/jenkinsci/libvirt-slave-plugin/pull/21 can be applied here. too

**Comment by yateya** [comment]
Hi. Thanks for the nice plugin.

I got same error. Here are my jenkins details:

- proxmox plugin version 0.4.1
- Jenkins latest version 2.303.1
- Ubuntu 20
- openjdk-11-jdk-headless version 11.0.11

> 2021-08-31 15:27:29.212+0000 [id=61]    WARNING h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID a32e9cdf-04cf-4aed-aaa5-5d774ffecaff
org.kohsuke.stapler.NoStaplerConstructorException: There's no @DataBoundConstructor on any constructor of class hudson.slaves.ComputerLauncher
        at org.kohsuke.stapler.ClassDescriptor.loadConstructorParamNames(ClassDescriptor.java:289)
        at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:786)
        at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:85)
        at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:690)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class hudson.slaves.ComputerLauncher from {"workDirSettings":{"disabled":false,"workDirPath":"","internalDir":"remoting","failIfWorkDirIsMissing":false},"webSocket":true,"tunnel":"","vmargs":""}
        at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:693)
        at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:490)
        at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:799)
Caused: java.lang.IllegalArgumentException: Failed to convert the delegateLauncher parameter of the constructor public org.jenkinsci.plugins.proxmox.VirtualMachineSlave(java.lang.String,java.lang.String,java.lang.String,java.lang.String,hudson.model.Node$Mode,java.lang.String,hudson.slaves.ComputerLauncher,hudson.slaves.RetentionStrategy,java.util.List,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.Boolean,int,org.jenkinsci.plugins.proxmox.VirtualMachineLauncher$RevertPolicy) throws hudson.model.Descriptor$FormException,java.io.IOException
        at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:801)
        at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:85)
        at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:690)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class org.jenkinsci.plugins.proxmox.VirtualMachineSlave from {"name":"proxmox1","datacenterDescription":"root@pam - 192.168.10.220","datacenterNode":"prox1","virtualMachineId":"102","snapshotName":"current","startVM":true,"revertPolicy":"AFTER_CONNECT","nodeDescription":"","startupWaitingPeriodSeconds":"60","numExecutors":"1","remoteFS":"/home/jenkins","labelString":"proxmox1","mode":"NORMAL","":["hudson.slaves.JNLPLauncher","hudson.slaves.RetentionStrategy$Always"],"delegateLauncher":{"workDirSettings":{"disabled":false,"workDirPath":"","internalDir":"remoting","failIfWorkDirIsMissing":false},"webSocket":true,"tunnel":"","vmargs":""},"nodeProperties":{"stapler-class-bag":"true"},"type":"org.jenkinsci.plugins.proxmox.VirtualMachineSlave","Jenkins-Crumb":"e2c9f645487cb13c3688df699fe4b7feb4346125ca0e1a9c80a3f8c023629cb8"}
        at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:693)
        at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:490)
        at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:486)
        at hudson.model.Descriptor.newInstance(Descriptor.java:607)
Caused: java.lang.LinkageError: Failed to instantiate class org.jenkinsci.plugins.proxmox.VirtualMachineSlave from {"name":"proxmox1","datacenterDescription":"root@pam - 192.168.10.220","datacenterNode":"prox1","virtualMachineId":"102","snapshotName":"current","startVM":true,"revertPolicy":"AFTER_CONNECT","nodeDescription":"","startupWaitingPeriodSeconds":"60","numExecutors":"1","remoteFS":"/home/jenkins","labelString":"proxmox1","mode":"NORMAL","":["hudson.slaves.JNLPLauncher","hudson.slaves.RetentionStrategy$Always"],"delegateLauncher":{"workDirSettings":{"disabled":false,"workDirPath":"","internalDir":"remoting","failIfWorkDirIsMissing":false},"webSocket":true,"tunnel":"","vmargs":""},"nodeProperties":{"stapler-class-bag":"true"},"type":"org.jenkinsci.plugins.proxmox.VirtualMachineSlave","Jenkins-Crumb":"e2c9f645487cb13c3688df699fe4b7feb4346125ca0e1a9c80a3f8c023629cb8"}
        at hudson.model.Descriptor.newInstance(Descriptor.java:613)
        at hudson.model.ComputerSet.doDoCreateItem(ComputerSet.java:304)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:393)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:405)

**Comment by Maxhy** [comment]
Indeed, the fix was incomplete. Should be fine now with v0.4.2, can you confirm @yateya?

**Comment by yateya** [comment]
Yes. Updating to v0.4.2 fixed the problem. Thanks :+1:

**Comment by yuvalattar1974** [comment]
is there any progress on proxmox plugin for jenkins for dynamic slaves using a proxmox template ?
